### ISSUE TITLE
what to do with it??? Kindly help

### ISSUE THREAD

**Issue by deb-cod** [jackfrost1411/fire-detection#3]
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[<ipython-input-47-34027101cc71>](https://localhost:8080/#) in <module>()
      6 from keras.applications.inception_v3 import InceptionV3
      7 #Load the saved model
----> 8 model = tf.keras.models.load_model('InceptionV3.h5')
      9 video = cv2.VideoCapture(0)
     10 while True:

1 frames
[/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py](https://localhost:8080/#) in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

[/usr/local/lib/python3.7/dist-packages/keras/saving/save.py](https://localhost:8080/#) in load_model(filepath, custom_objects, compile, options)
    202         if isinstance(filepath_str, str):
    203           if not tf.io.gfile.exists(filepath_str):
--> 204             raise IOError(f'No file or directory found at {filepath_str}')
    205 
    206           if tf.io.gfile.isdir(filepath_str):

OSError: No file or directory found at InceptionV3.h5

**Comment by alysamariereyes** [comment]
Good day, I am having the same issue here. Did you fix it already?

**Comment by Anurag15v** [comment]
Yep same error man? Please fix this.

**Comment by jackfrost1411** [comment]
Train and give the path to your trained model there.
